"use client";

import { useEffect, useState } from "react";

type Course = { id: string; courseCode: string; courseTitle: string; description: string | null; unit: number | null; semester: string | null; academicSession: string | null; enrolled: boolean; enrolledCount: number };

export default function StudentCoursesPage() {
  const [courses, setCourses] = useState<Course[]>([]);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState("");
  useEffect(() => { fetch("/api/student/courses").then(async (response) => { if (!response.ok) throw new Error(); return response.json(); }).then((payload) => setCourses(payload.data ?? [])).catch(() => setError("Unable to load course registration.")); }, []);
  async function enroll(courseId: string) { setBusy(courseId); const response = await fetch("/api/student/courses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ courseId }) }); if (!response.ok) setError("Unable to register for this course."); else setCourses((items) => items.map((course) => course.id === courseId ? { ...course, enrolled: true, enrolledCount: course.enrolledCount + 1 } : course)); setBusy(""); }
  return <main className="min-h-screen bg-[var(--background)] px-5 py-8 text-[var(--ink)] md:px-10"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--outline)]">Registration</p><h1 className="mt-2 font-[Manrope] text-3xl font-extrabold text-[var(--primary)]">Course registration</h1><p className="mt-2 text-sm text-[var(--muted)]">Choose the published courses relevant to your current academic session.</p>{error && <p className="mt-5 text-sm text-red-700" role="alert">{error}</p>}<div className="mt-8 grid gap-4 md:grid-cols-2">{courses.map((course) => <article className="rounded-lg border border-[var(--outline-light)] bg-[var(--surface)] p-5 shadow-sm" key={course.id}><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-[var(--primary)]">{course.courseCode}</p><h2 className="mt-1 font-[Manrope] text-xl font-bold">{course.courseTitle}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${course.enrolled ? "bg-green-100 text-green-700" : "bg-[var(--surface-low)] text-[var(--muted)]"}`}>{course.enrolled ? "Registered" : "Available"}</span></div><p className="mt-4 text-sm text-[var(--muted)]">{course.description ?? "Course description not provided."}</p><p className="mt-4 text-xs text-[var(--outline)]">{course.unit ?? "-"} units · {course.semester ?? "Current semester"} · {course.enrolledCount} registered</p>{!course.enrolled && <button className="mt-5 rounded-md bg-[var(--primary)] px-4 py-2 text-sm font-bold text-white disabled:opacity-50" type="button" disabled={busy === course.id} onClick={() => enroll(course.id)}>{busy === course.id ? "Registering..." : "Register for course"}</button>}</article>)}{!courses.length && !error && <p className="text-sm text-[var(--muted)]">No courses are currently published.</p>}</div></div></main>;
}
