"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { getBrowserLocation } from "@/src/lib/browser-location";

type Course = { id: string; courseCode: string; courseTitle: string; unit: number | null; studentCount: number; sessionCount: number; latestSession: { id: string; isOpen: boolean } | null };

export default function LecturerCoursesPage() {
  const [courses, setCourses] = useState<Course[]>([]);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState("");
  async function loadCourses() { const response = await fetch("/api/lecturer/courses"); if (!response.ok) throw new Error(); const payload = await response.json(); setCourses(payload.data ?? []); }
  useEffect(() => { const timer = window.setTimeout(() => loadCourses().catch(() => setError("Unable to load assigned courses.")), 0); return () => window.clearTimeout(timer); }, []);
  async function openAttendance(courseId: string) { setBusy(courseId); try { const location = await getBrowserLocation(); const response = await fetch(`/api/lecturer/courses/${courseId}/sessions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ date: new Date().toISOString().slice(0, 10), ...location }) }); if (!response.ok) { const payload = await response.json().catch(() => null); setError(payload?.error ?? "Unable to open attendance for this course."); } else await loadCourses(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to obtain lecturer location."); } finally { setBusy(""); } }
  async function updateAttendance(sessionId: string, action: "close" | "reopen", courseId: string) { setBusy(courseId); const response = await fetch(`/api/lecturer/sessions/${sessionId}/${action}`, { method: "PATCH" }); if (!response.ok) setError(`Unable to ${action} attendance for this course.`); else await loadCourses(); setBusy(""); }
  return <main className="mx-auto max-w-7xl px-6 py-8 md:px-10"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--outline)]">Teaching load</p><h1 className="mt-2 font-[Manrope] text-3xl font-extrabold text-[var(--primary)]">My Courses</h1><p className="mt-2 text-sm text-[var(--muted)]">Only courses assigned to your lecturer account are shown.</p>{error && <p className="mt-5 text-sm text-[var(--error)]" role="alert">{error}</p>}<div className="mt-8 grid gap-4 lg:grid-cols-2">{courses.map((course) => <article className="rounded-lg border border-[var(--outline-light)] bg-[var(--surface)] p-5 shadow-sm" key={course.id}><p className="text-sm font-bold text-[var(--primary)]">{course.courseCode}</p><h2 className="mt-1 font-[Manrope] text-xl font-bold">{course.courseTitle}</h2><p className="mt-4 text-sm text-[var(--muted)]">{course.unit ?? "-"} units · {course.studentCount} students · {course.sessionCount} sessions</p><div className="mt-5 flex flex-wrap gap-2">{!course.latestSession && <button className="rounded-md bg-[var(--primary)] px-3 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={busy === course.id} onClick={() => openAttendance(course.id)} type="button">Open Attendance</button>}{course.latestSession?.isOpen && <button className="rounded-md bg-[var(--primary)] px-3 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={busy === course.id} onClick={() => updateAttendance(course.latestSession!.id, "close", course.id)} type="button">Close Attendance</button>}{course.latestSession && !course.latestSession.isOpen && <button className="rounded-md border border-[var(--primary)] px-3 py-2 text-sm font-bold text-[var(--primary)] disabled:opacity-50" disabled={busy === course.id} onClick={() => updateAttendance(course.latestSession!.id, "reopen", course.id)} type="button">Reopen Attendance</button>}{course.latestSession && <Link className="rounded-md border border-[var(--secondary)] px-3 py-2 text-sm font-bold text-[var(--primary)]" href={`/lecturer/courses/${course.id}/live`}>Live roster</Link>}</div></article>)}</div></main>;
}
