"use client";

import { useEffect, useState } from "react";

type User = { id: string; fullName: string; email: string; isActive: boolean; _count: { complaints: number } };
export default function AdminLecturersPage() {
  const [users, setUsers] = useState<User[]>([]); const [search, setSearch] = useState(""); const [error, setError] = useState("");
  async function load() { const response = await fetch(`/api/admin/users?role=LECTURER&search=${encodeURIComponent(search)}`); if (!response.ok) throw new Error(); const payload = await response.json(); setUsers(payload.data?.users ?? []); }
  useEffect(() => { fetch("/api/admin/users?role=LECTURER").then(async (response) => { if (!response.ok) throw new Error(); return response.json(); }).then((payload) => setUsers(payload.data?.users ?? [])).catch(() => setError("Unable to load lecturers.")); }, []);
  async function toggle(user: User) { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId: user.id, isActive: !user.isActive }) }); if (!response.ok) { setError("Unable to update account status."); return; } setUsers((items) => items.map((item) => item.id === user.id ? { ...item, isActive: !item.isActive } : item)); }
  return <main className="min-h-screen bg-[var(--background)] px-5 py-8 text-[var(--ink)] md:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--outline)]">Directory</p><h1 className="mt-2 font-[Manrope] text-3xl font-extrabold text-[var(--primary)]">Lecturers</h1><p className="mt-2 text-sm text-[var(--muted)]">Manage lecturer accounts used for course allocation and complaint triage.</p><form className="mt-7 flex max-w-xl gap-2" onSubmit={(event) => { event.preventDefault(); load().catch(() => setError("Unable to load lecturers.")); }}><input className="min-w-0 flex-1 rounded-md border border-[var(--outline-light)] bg-[var(--surface)] px-4 py-3 text-sm" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search lecturer name or email" /><button className="rounded-md bg-[var(--primary)] px-4 py-2 text-sm font-bold text-white" type="submit">Search</button></form>{error && <p className="mt-4 text-sm text-red-700" role="alert">{error}</p>}<div className="mt-7 overflow-x-auto rounded-lg border border-[var(--outline-light)] bg-[var(--surface)] shadow-sm"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[var(--surface-low)] text-xs uppercase tracking-wide text-[var(--outline)]"><tr><th className="px-5 py-3">Lecturer</th><th className="px-5 py-3">Complaints</th><th className="px-5 py-3">Account</th><th className="px-5 py-3">Action</th></tr></thead><tbody className="divide-y divide-[var(--outline-light)]">{users.map((user) => <tr key={user.id}><td className="px-5 py-4"><strong>{user.fullName}</strong><span className="mt-1 block text-[var(--muted)]">{user.email}</span></td><td className="px-5 py-4">{user._count.complaints}</td><td className="px-5 py-4">{user.isActive ? "Active" : "Inactive"}</td><td className="px-5 py-4"><button className="rounded-md border border-[var(--primary)] px-3 py-2 text-xs font-bold text-[var(--primary)]" type="button" onClick={() => toggle(user)}>{user.isActive ? "Deactivate" : "Activate"}</button></td></tr>)}</tbody></table></div></div></main>;
}
