"use client";

import { useEffect, useState } from "react";

type Course = { id: string; courseCode: string; courseTitle: string; unit: number | null; _count: { enrollments: number; attendanceSessions: number; lecturerAssignments: number }; lecturerAssignments: Array<{ lecturer: { fullName: string } }> };

export default function AdminCoursesPage() {
  const [courses, setCourses] = useState<Course[]>([]);
  const [search, setSearch] = useState("");
  const [error, setError] = useState("");
  async function load() { const response = await fetch(`/api/admin/courses?search=${encodeURIComponent(search)}`); if (!response.ok) throw new Error(); const payload = await response.json(); setCourses(payload.data ?? []); }
  useEffect(() => { fetch("/api/admin/courses").then(async (response) => { if (!response.ok) throw new Error(); return response.json(); }).then((payload) => setCourses(payload.data ?? [])).catch(() => setError("Unable to load courses.")); }, []);
  return <main className="min-h-screen bg-[var(--background)] px-5 py-8 text-[var(--ink)] md:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--outline)]">Academic catalogue</p><h1 className="mt-2 font-[Manrope] text-3xl font-extrabold text-[var(--primary)]">Courses</h1><p className="mt-2 text-sm text-[var(--muted)]">Review course capacity and lecturer allocation.</p><form className="mt-7 flex max-w-xl gap-2" onSubmit={(event) => { event.preventDefault(); load().catch(() => setError("Unable to load courses.")); }}><input className="min-w-0 flex-1 rounded-md border border-[var(--outline-light)] bg-[var(--surface)] px-4 py-3 text-sm" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by code or title" /><button className="rounded-md bg-[var(--primary)] px-4 py-2 text-sm font-bold text-white" type="submit">Search</button></form>{error && <p className="mt-4 text-sm text-red-700" role="alert">{error}</p>}<div className="mt-7 overflow-x-auto rounded-lg border border-[var(--outline-light)] bg-[var(--surface)] shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[var(--surface-low)] text-xs uppercase tracking-wide text-[var(--outline)]"><tr><th className="px-5 py-3">Course</th><th className="px-5 py-3">Lecturer</th><th className="px-5 py-3">Students</th><th className="px-5 py-3">Sessions</th></tr></thead><tbody className="divide-y divide-[var(--outline-light)]">{courses.map((course) => <tr key={course.id}><td className="px-5 py-4"><strong className="text-[var(--primary)]">{course.courseCode}</strong><span className="mt-1 block">{course.courseTitle} · {course.unit ?? "-"} units</span></td><td className="px-5 py-4 text-[var(--muted)]">{course.lecturerAssignments.map((item) => item.lecturer.fullName).join(", ") || "Unassigned"}</td><td className="px-5 py-4">{course._count.enrollments}</td><td className="px-5 py-4">{course._count.attendanceSessions}</td></tr>)}</tbody></table></div></div></main>;
}
