"use client";

import { useEffect, useState } from "react";

type ReportRow = { student: { fullName: string; matricNumber: string | null }; course: { courseCode: string; courseTitle: string }; totalSessions: number; attended: number; attendancePercentage: number | null; eligibility: { status: "GOOD TO GO" | "INELIGIBLE" | "NO DATA" } };
export default function AdminReportsPage() {
  const [report, setReport] = useState<ReportRow[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/reports/attendance").then(async (response) => { if (!response.ok) throw new Error(); return response.json(); }).then((payload) => setReport(payload.data)).catch(() => setError("Unable to load attendance reports.")); }, []);
  return <main className="min-h-screen bg-[var(--background)] px-5 py-8 text-[var(--ink)] md:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--outline)]">Insights</p><h1 className="mt-2 font-[Manrope] text-3xl font-extrabold text-[var(--primary)]">Attendance reports</h1><p className="mt-2 text-sm text-[var(--muted)]">System-wide attendance performance and eligibility by student and course.</p><a className="mt-6 inline-flex rounded-md bg-[var(--primary)] px-4 py-2 text-sm font-bold text-white" href="/api/admin/attendance?format=csv">Download attendance CSV</a>{error && <p className="mt-5 text-sm text-red-700" role="alert">{error}</p>}<div className="mt-8 overflow-x-auto rounded-lg border border-[var(--outline-light)] bg-[var(--surface)] shadow-sm"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-[var(--surface-low)] text-xs uppercase tracking-wide text-[var(--outline)]"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Course</th><th className="px-5 py-3">Attendance</th><th className="px-5 py-3">Eligibility</th></tr></thead><tbody className="divide-y divide-[var(--outline-light)]">{report.map((row) => <tr key={`${row.student.matricNumber}-${row.course.courseCode}`}><td className="px-5 py-4">{row.student.fullName}<span className="mt-1 block text-[var(--muted)]">{row.student.matricNumber ?? "No matric"}</span></td><td className="px-5 py-4">{row.course.courseCode} · {row.course.courseTitle}</td><td className="px-5 py-4">{row.attended}/{row.totalSessions} · {row.attendancePercentage ?? 0}%</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${row.eligibility.status === "GOOD TO GO" ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"}`}>{row.eligibility.status}</span></td></tr>)}</tbody></table></div></div></main>;
}
