"use client";

import { useEffect, useState } from "react";

type Profile = { fullName: string; email: string; matricNumber: string | null; role: string };

export default function SettingsPage() {
	const [profile, setProfile] = useState<Profile | null>(null);
	const [fullName, setFullName] = useState("");
	const [currentPassword, setCurrentPassword] = useState("");
	const [newPassword, setNewPassword] = useState("");
	const [confirmPassword, setConfirmPassword] = useState("");
	const [message, setMessage] = useState("");
	const [error, setError] = useState("");
	useEffect(() => { const timer = window.setTimeout(() => fetch("/api/settings/profile").then((response) => response.json()).then((payload) => { if (!payload.data) throw new Error(); setProfile(payload.data); setFullName(payload.data.fullName); }).catch(() => setError("Unable to load settings.")), 0); return () => window.clearTimeout(timer); }, []);
	async function saveProfile() { const response = await fetch("/api/settings/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName }) }); if (!response.ok) { setError("Unable to update profile."); return; } setProfile((await response.json()).data); setMessage("Profile updated."); }
	async function changePassword(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const response = await fetch("/api/settings/password", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword, newPassword, confirmPassword }) }); if (!response.ok) { const payload = await response.json(); setError(payload.error ?? "Unable to update password."); return; } setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); setMessage("Password updated."); }
	return <main className="mx-auto max-w-4xl px-5 py-8 text-[var(--ink)] md:px-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--outline)]">Account</p><h1 className="mt-2 font-[Manrope] text-3xl font-extrabold text-[var(--primary)]">Settings</h1><p className="mt-2 text-sm text-[var(--muted)]">Manage your profile and account security.</p>{message && <p className="mt-5 text-sm text-green-700" role="status">{message}</p>}{error && <p className="mt-5 text-sm text-red-700" role="alert">{error}</p>}<section className="mt-8 rounded-lg border border-[var(--outline-light)] bg-[var(--surface)] p-6 shadow-sm"><h2 className="font-[Manrope] text-xl font-bold">Profile</h2>{profile && <div className="mt-5 grid gap-4"><label className="text-sm font-semibold">Full name<input className="mt-2 min-h-11 w-full rounded-md border border-[var(--outline-light)] bg-[var(--background)] px-3 font-normal" value={fullName} onChange={(event) => setFullName(event.target.value)} /></label><label className="text-sm font-semibold">Email<input className="mt-2 min-h-11 w-full rounded-md border border-[var(--outline-light)] bg-[var(--surface-low)] px-3 font-normal" value={profile.email} readOnly /></label><p className="text-sm text-[var(--muted)]">{profile.role} · {profile.matricNumber ?? ""}</p><button className="w-fit rounded-md bg-[var(--primary)] px-4 py-2 text-sm font-bold text-white" type="button" onClick={saveProfile}>Save profile</button></div>}</section><form className="mt-5 rounded-lg border border-[var(--outline-light)] bg-[var(--surface)] p-6 shadow-sm" onSubmit={changePassword}><h2 className="font-[Manrope] text-xl font-bold">Change password</h2><div className="mt-5 grid gap-4"><input className="rounded-md border border-[var(--outline-light)] bg-[var(--background)] px-3 py-3 text-sm" type="password" placeholder="Current password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} required /><input className="rounded-md border border-[var(--outline-light)] bg-[var(--background)] px-3 py-3 text-sm" type="password" placeholder="New password" minLength={8} value={newPassword} onChange={(event) => setNewPassword(event.target.value)} required /><input className="rounded-md border border-[var(--outline-light)] bg-[var(--background)] px-3 py-3 text-sm" type="password" placeholder="Confirm new password" minLength={8} value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required /><button className="w-fit rounded-md bg-[var(--primary)] px-4 py-2 text-sm font-bold text-white" type="submit">Change password</button></div></form></main>;
}
