"use client";

import { useEffect, useState } from "react";

type Profile = { fullName: string; email: string; matricNumber: string | null; role: string; avatarUrl: string | null };

export default function SettingsPage() {
  const [profile, setProfile] = useState<Profile | null>(null); const [fullName, setFullName] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/settings/profile"); if (!response.ok) throw new Error(); const data = (await response.json()).data; setProfile(data); setFullName(data.fullName); }
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch(() => setError("Unable to load settings.")); }, 0); return () => window.clearTimeout(timer); }, []);
  async function saveProfile() { setBusy(true); setError(""); try { const response = await fetch("/api/settings/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? "Unable to update profile."); setProfile(payload.data); setMessage("Profile updated."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update profile."); } finally { setBusy(false); } }
  async function upload(file: File) { if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 5 * 1024 * 1024) { setError("Choose a JPG, PNG, or WebP image smaller than 5 MB."); return; } setBusy(true); setError(""); try { const body = new FormData(); body.append("file", file); const response = await fetch("/api/settings/profile/avatar", { method: "POST", body }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? "Upload failed."); setProfile((current) => current ? { ...current, avatarUrl: payload.data.avatarUrl } : current); setMessage("Profile photo uploaded."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed."); } finally { setBusy(false); } }
  const initials = profile?.fullName.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase() ?? "ST";
  return <main className="dashboard-main"><div className="prototype-content"><div className="page-intro"><p className="eyebrow">ACCOUNT</p><h2>Settings</h2><p>Manage your personal details and profile photo.</p></div>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}{!profile ? <div className="empty-state card">Loading settings...</div> : <section className="settings-panel card"><div className="settings-avatar"><label className="avatar-button cursor-pointer">{profile.avatarUrl ? <><span className="sr-only">Profile photo</span>{/* eslint-disable-next-line @next/next/no-img-element */}<img className="avatar avatar-large" src={profile.avatarUrl} alt={`${profile.fullName} profile`} /></> : <div className="avatar avatar-large">{initials}</div>}<span>{busy ? "Uploading..." : "Change photo"}</span><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.currentTarget.value = ""; }} /></label><div><strong>{profile.fullName}</strong><p>JPG, PNG, or WebP up to 5 MB.</p></div></div><div className="settings-form"><label>Full name<input value={fullName} onChange={(event) => setFullName(event.target.value)} /></label><label>Email<input value={profile.email} readOnly /></label><label>Role<input value={profile.role} readOnly /></label><label>Matric number<input value={profile.matricNumber ?? "Not provided"} readOnly /></label></div><button className="primary-button" type="button" onClick={() => void saveProfile()} disabled={busy}>{busy ? "Saving..." : "Save profile"}</button></section>}</div></main>;
}
