"use client";

import { useEffect, useState } from "react";

type Student = { id: string; fullName: string; matricNumber: string | null; record: { status: string; createdAt: string } | null };
type LiveData = { session: { id: string; isOpen: boolean; course: { courseCode: string; courseTitle: string } }; students: Student[] };

export default function LecturerLiveRosterPage({ params }: { params: Promise<{ courseId: string }> }) {
  const [data, setData] = useState<LiveData | null>(null); const [error, setError] = useState(""); const [sessionId, setSessionId] = useState("");
  async function load(courseId: string) { const coursesResponse = await fetch("/api/lecturer/courses"); const payload = await coursesResponse.json(); const course = (payload.data ?? []).find((item: { id: string }) => item.id === courseId); if (!course?.latestSession?.id) throw new Error("No attendance session is available."); setSessionId(course.latestSession.id); const response = await fetch(`/api/lecturer/sessions/${course.latestSession.id}/live`); if (!response.ok) throw new Error(); setData((await response.json()).data); }
  useEffect(() => { params.then(({ courseId }) => load(courseId).catch(() => setError("Unable to load the live roster."))); }, [params]);
  useEffect(() => { if (!sessionId) return; const timer = window.setInterval(() => fetch(`/api/lecturer/sessions/${sessionId}/live`).then((response) => response.ok ? response.json() : null).then((payload) => payload?.data && setData(payload.data)).catch(() => undefined), 3000); return () => window.clearInterval(timer); }, [sessionId]);
  async function mark(studentId: string, status: "PRESENT" | "ABSENT") { const response = await fetch(`/api/lecturer/sessions/${sessionId}/attendance`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentId, status }) }); if (!response.ok) { setError("Unable to update attendance."); return; } const payload = await fetch(`/api/lecturer/sessions/${sessionId}/live`).then((result) => result.json()); setData(payload.data); }
  return <main className="mx-auto max-w-6xl px-5 py-8 md:px-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--outline)]">Live session</p><h1 className="mt-2 font-[Manrope] text-3xl font-extrabold text-[var(--primary)]">Attendance roster</h1>{error && <p className="mt-5 text-sm text-red-700" role="alert">{error}</p>}{data && <section className="mt-7 overflow-x-auto rounded-lg border border-[var(--outline-light)] bg-[var(--surface)] shadow-sm"><div className="border-b border-[var(--outline-light)] px-5 py-4"><h2 className="font-[Manrope] text-xl font-bold">{data.session.course.courseCode} · {data.session.course.courseTitle}</h2><p className="mt-1 text-sm text-[var(--muted)]">{data.session.isOpen ? "Attendance is open" : "Attendance is closed"}</p></div><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[var(--surface-low)] text-xs uppercase tracking-wide text-[var(--outline)]"><tr><th className="px-5 py-3">Student name</th><th className="px-5 py-3">Matric number</th><th className="px-5 py-3">Attendance status</th><th className="px-5 py-3">Time marked</th><th className="px-5 py-3">Override</th></tr></thead><tbody className="divide-y divide-[var(--outline-light)]">{data.students.map((student) => <tr key={student.id}><td className="px-5 py-4">{student.fullName}</td><td className="px-5 py-4 text-[var(--muted)]">{student.matricNumber ?? "Not provided"}</td><td className="px-5 py-4">{student.record?.status ?? "ABSENT"}</td><td className="px-5 py-4 text-[var(--muted)]">{student.record ? new Date(student.record.createdAt).toLocaleTimeString() : "Not marked"}</td><td className="px-5 py-4"><button className="mr-2 rounded-md bg-[var(--primary)] px-3 py-2 text-xs font-bold text-white disabled:opacity-50" disabled={!data.session.isOpen} type="button" onClick={() => mark(student.id, "PRESENT")}>Mark Present</button><button className="rounded-md border border-[var(--primary)] px-3 py-2 text-xs font-bold text-[var(--primary)] disabled:opacity-50" disabled={!data.session.isOpen} type="button" onClick={() => mark(student.id, "ABSENT")}>Mark Absent</button></td></tr>)}</tbody></table></section>}</main>;
}
