"use client";

import { useEffect, useState } from "react";

type Profile = { fullName: string; email: string; role: string };

export default function LecturerSettingsPage() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [fullName, setFullName] = useState("");
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/settings/profile").then((response) => response.json()).then((payload) => { if (!payload.data) throw new Error(); setProfile(payload.data); setFullName(payload.data.fullName); }).catch(() => setError("Unable to load your profile.")); }, []);
  async function saveProfile() { const response = await fetch("/api/settings/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName }) }); if (!response.ok) { setError("Unable to update your profile."); return; } setProfile((await response.json()).data); setMessage("Profile updated."); }
  async function changePassword(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/settings/password", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword, newPassword }) }); if (!response.ok) { const payload = await response.json(); setError(payload.error ?? "Unable to update password."); return; } setCurrentPassword(""); setNewPassword(""); setMessage("Password updated."); }
  return <main className="mx-auto max-w-4xl px-6 py-8 md:px-10"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--outline)]">Account</p><h1 className="mt-2 font-[Manrope] text-3xl font-extrabold text-[var(--primary)]">Settings</h1><p className="mt-2 text-sm text-[var(--muted)]">Review your lecturer profile and update account security.</p>{message && <p className="mt-5 text-sm text-green-700">{message}</p>}{error && <p className="mt-5 text-sm text-[var(--error)]" role="alert">{error}</p>}<section className="mt-8 rounded-lg border border-[var(--outline-light)] bg-[var(--surface)] p-6 shadow-sm"><h2 className="font-[Manrope] text-xl font-bold">Profile</h2>{profile && <div className="mt-5 grid gap-4"><label className="text-sm font-semibold">Full name<input className="mt-2 min-h-11 w-full rounded-md border border-[var(--outline-light)] bg-[var(--background)] px-3 font-normal" value={fullName} onChange={(event) => setFullName(event.target.value)} /></label><label className="text-sm font-semibold">Email<input className="mt-2 min-h-11 w-full rounded-md border border-[var(--outline-light)] bg-[var(--surface-low)] px-3 font-normal" value={profile.email} readOnly /></label><p className="text-sm text-[var(--muted)]">Role: {profile.role}</p><button className="w-fit rounded-md bg-[var(--primary)] px-4 py-2 text-sm font-bold text-white" onClick={saveProfile} type="button">Save profile</button></div>}</section><form className="mt-5 rounded-lg border border-[var(--outline-light)] bg-[var(--surface)] p-6 shadow-sm" onSubmit={changePassword}><h2 className="font-[Manrope] text-xl font-bold">Password</h2><div className="mt-5 grid gap-4"><label className="text-sm font-semibold">Current password<input className="mt-2 min-h-11 w-full rounded-md border border-[var(--outline-light)] bg-[var(--background)] px-3 font-normal" type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} required /></label><label className="text-sm font-semibold">New password<input className="mt-2 min-h-11 w-full rounded-md border border-[var(--outline-light)] bg-[var(--background)] px-3 font-normal" type="password" minLength={8} value={newPassword} onChange={(event) => setNewPassword(event.target.value)} required /></label><button className="w-fit rounded-md border border-[var(--primary)] px-4 py-2 text-sm font-bold text-[var(--primary)]" type="submit">Update password</button></div></form></main>;
}
